package com.epam.kostiuk.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-09-10T18:21:55.514+03:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://webservice.kostiuk.epam.com/", name = "calculator")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Calculator {

    @WebMethod
    public void sub(
        @WebParam(partName = "value1", name = "value1")
        float value1,
        @WebParam(partName = "value2", name = "value2")
        float value2,
        @WebParam(partName = "result", mode = WebParam.Mode.OUT, name = "result")
        javax.xml.ws.Holder<java.lang.Double> result
    );

    @WebMethod
    public void mul(
        @WebParam(partName = "value1", name = "value1")
        float value1,
        @WebParam(partName = "value2", name = "value2")
        float value2,
        @WebParam(partName = "result", mode = WebParam.Mode.OUT, name = "result")
        javax.xml.ws.Holder<java.lang.Double> result
    );

    @WebMethod
    public void div(
        @WebParam(partName = "value1", name = "value1")
        float value1,
        @WebParam(partName = "value2", name = "value2")
        float value2,
        @WebParam(partName = "result", mode = WebParam.Mode.OUT, name = "result")
        javax.xml.ws.Holder<java.lang.Double> result
    );

    @WebMethod
    public void pow(
        @WebParam(partName = "value1", name = "value1")
        float value1,
        @WebParam(partName = "value2", name = "value2")
        float value2,
        @WebParam(partName = "result", mode = WebParam.Mode.OUT, name = "result")
        javax.xml.ws.Holder<java.lang.Double> result
    );

    @WebMethod
    public void add(
        @WebParam(partName = "value1", name = "value1")
        float value1,
        @WebParam(partName = "value2", name = "value2")
        float value2,
        @WebParam(partName = "result", mode = WebParam.Mode.OUT, name = "result")
        javax.xml.ws.Holder<java.lang.Double> result
    );
}
